### ISSUE TITLE
False negative when Cloudflare is checking browser

### ISSUE THREAD

**Issue by Juribiyan** [fenhl/isup#1]
Under some circumstances Cloudflare performs a browser check before allowing you to proceed to the website no matter whether it is online or off. Isup.me always says the website is off. I'm not sure if it's possible to pass the browser check but at least the service should return the undefined state in that situation.

Example: http://1chan.ru

**Comment by fenhl** [comment]
I'm sorry but since this script just scrapes isup.me, there is nothing I can do about this. You would have to contact the creator(s) of isup.me to ask them to fix this.

**Comment by Juribiyan** [comment]
I thought you are the creator of isup.me. Should have read the description more carefully. Sorry
